# 应用端口
server:
  port: 8080
# 应用名
spring:
  application:
    name: rocketmq-demo


# rocketmq 配置
rocketmq:
  # rocketmq 服务地址集群由 `;`分开
  name-server: http://192.168.37.131:9876
  # 自定义的组名称
  producer:
    group: producer_test
    # 消息发送超时时长
    send-message-timeout: 5000
